# cp.spec.Error

Provides an Error message, which can be thrown via the `error` function.

---

## API Overview
**Functions** - _API calls offered directly by the extension_
 * [is](#is)


---

## API Documentation

#### Functions


### [is](#is)

|                                             |                                                                                     |
| --------------------------------------------|-------------------------------------------------------------------------------------|
| **Signature**                               | `cp.spec.Error.is(other) -> boolean`                                                                    |
| **Type**                                    | Function                                                                     |
| **Description**                             | Checks if the `other` is an instance of the `Error` class.                                                                     |
| **Parameters**                              | <ul><li>other - An object to check</li></ul> |
| **Returns**                                 | <ul><li>A boolean</li></ul>          |
| **Notes**                                   | None |
| **Examples**                                | None |
| **Source**                                  | [src/extensions/cp/spec/Error.lua line 9](https://github.com/CommandPost/CommandPost/blob/develop/src/extensions/cp/spec/Error.lua#L9) |

---

